---
- hosts: all
  become: yes
  tasks:
    - name: Create /better-place directory
      file:
        path: /better-place
        state: directory

    - name: Create user
      user:
        name: john
        comment: John Doe
        uid: 1234
        home: /better-place/john

    - name: Create nice-script.sh
      copy:
        dest: "/etc/skel/nice-script.sh"
        content: "#!/bin/bash\ndf -h"
        mode: 0755

    - name: Allow john to run whoami with sudo without a password
      lineinfile:
        dest: /etc/sudoers
        line: 'john ALL=(ALL) NOPASSWD: /usr/bin/whoami'

    - name: Install packages
      package:
        name:
          - tmux
          - vim
        state: present

    - name: Install Terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/0.14.7/terraform_0.14.7_linux_amd64.zip
        dest: /usr/local/bin/
        remote_src: yes
        creates: /usr/local/bin/terraform
