name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 19 * * 6"

env:
  DOCKER_HUB_USERNAME: <your_dockerhub_username>
  DOCKER_HUB_PASSWORD: <your_dockerhub_password>

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            <your_dockerhub_username>/flask-app:latest
            <your_dockerhub_username>/flask-app:${{ github.sha }}
            <your_dockerhub_username>/flask-app:main

        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        