name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 19 * * 6'  # every Saturday at 7 PM

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Convert repo name to lower case
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | awk '{print tolower($0)}')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/$REPO_NAME/app:latest .
          docker push ghcr.io/$REPO_NAME/app:latest
