name: TestStuff

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 19 * * 6'  # every Saturday at 7 PM

jobs:
  try-stop-cluster:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    - name: Check Azure CLI version
      run: az --version    
    - name: Azure Login
      uses: azure/login@v1 
      with:
        creds: ${{ secrets.AZURE_SELF_HOSTED_RUNNER_CREDENTIALS }}
    - name: Display Azure Account Info
      run: |
        az account show    